[package]
name = "sdui-runtime-wgpu"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sdui-core = { path = "../sdui-core" }
wgpu = { workspace = true }
glyphon = { workspace = true }
bytemuck = { version = "1", features = ["derive"] }
